version: "3.8"
services:
  web:
    build: .
    tty: true
    container_name: web
    volumes:
      - static:/back/static
    ports:
      - "8000:8000"
      - "4317:4317"
    entrypoint: ["sh", "./entrypoint.sh"]
    environment:
      - DEBUG=0

volumes:
  static: