# Generated by Django 2.2 on 2021-04-03 16:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=64)),
                ('site_discription', models.TextField(max_length=3072)),
                ('site_address', models.URLField()),
                ('author', models.CharField(max_length=32)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('is_verified', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.TextField(blank=True, max_length=300, null=True)),
                ('author', models.CharField(max_length=32)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.Link')),
            ],
        ),
    ]
