# Generated by Django 3.1.11 on 2021-06-09 00:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='region',
            field=models.CharField(default=datetime.datetime(2021, 6, 9, 0, 21, 43, 983256, tzinfo=utc), max_length=128),
            preserve_default=False,
        ),
    ]
