# Generated by Django 3.1.11 on 2021-07-02 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0002_link_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.RenameField(
            model_name='link',
            old_name='site_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='site_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='site_name',
            new_name='name',
        ),
    ]
