# Generated by Django 3.1.11 on 2021-07-03 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0003_auto_20210703_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.region'),
        ),
    ]
