# Generated by Django 3.1.11 on 2021-07-10 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0005_auto_20210707_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sources.region'),
        ),
    ]
